export interface OutputReadmeOptions { reportGenerated: boolean; pdfMessage: string }

export function renderOutputReadme(options: OutputReadmeOptions): string {
  return `# Supabase Performance Review Output

This directory was generated by the Supabase Performance Review CLI.

## Files

- **evidence.json** — normalized observed database evidence and optional hosted log data. It contains no database password or Supabase access token.
- **facts.md** — deterministic Markdown rendering of the observed database checks and log status. It contains facts, not remediation advice.
- **report.md** — detailed Markdown analysis generated by the configured external LLM command from a bounded, redacted evidence payload.
- **executive-summary.md** — non-technical summary generated from the detailed report.
- **analysis.json** — report metadata, command fingerprint, redaction/validation status, and copies of both Markdown reports.
- **report.pdf** — PDF conversion of report.md, when npx md-to-pdf was available.
- **executive-summary.pdf** — PDF conversion of executive-summary.md, when npx md-to-pdf was available.

${options.reportGenerated ? "Reports were generated only after the configured LLM command passed its validation step. The LLM received evidence through stdin; no recommendation was executed." : "No LLM reports were requested; only local evidence and facts were generated."}

PDF status: ${options.pdfMessage}

The database checks run embedded, read-only SQL. Hosted logs are optional and queried in UTC windows. Re-running report generation from evidence.json does not reconnect to PostgreSQL.
`;
}
