// SQL snapshot from Supabase CLI commit 713129cc1cd27c1d9371554d870c2972914ab12b.
// Source: https://raw.githubusercontent.com/supabase/cli/713129cc1cd27c1d9371554d870c2972914ab12b/apps/cli/src/legacy/commands/inspect/db/db-stats/db-stats.query.ts
import type { QueryDefinition } from "../registry";
import { SCHEMA_PATTERNS } from "../schemas";

export const query: QueryDefinition = {
  id: "db-stats",
  title: "Database statistics",
  sql: "WITH total_objects AS (\n  SELECT c.relkind, pg_size_pretty(SUM(pg_relation_size(c.oid))) AS size\n  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace\n  WHERE c.relkind IN ('i', 'r', 't') AND NOT n.nspname LIKE ANY($1)\n  GROUP BY c.relkind\n), cache_hit AS (\n  SELECT\n    'i' AS relkind,\n    ROUND(SUM(idx_blks_hit)::numeric / nullif(SUM(idx_blks_hit + idx_blks_read), 0), 2) AS ratio\n  FROM pg_statio_user_indexes\n  WHERE NOT schemaname LIKE ANY($1)\n    UNION\n  SELECT\n    't' AS relkind,\n    /*\n      Handle column names for both PG15 and 17\n    */\n    ROUND(\n      (\n        SUM(\n          COALESCE(\n            (to_jsonb(s) ->> 'rel_blks_hit')::bigint,\n            (to_jsonb(s) ->> 'heap_blks_hit')::bigint,\n            0\n          )\n        )::numeric\n        /\n        nullif(\n          SUM(\n            COALESCE(\n              (to_jsonb(s) ->> 'rel_blks_hit')::bigint,\n              (to_jsonb(s) ->> 'heap_blks_hit')::bigint,\n              0\n            )\n            +\n            COALESCE(\n              (to_jsonb(s) ->> 'rel_blks_read')::bigint,\n              (to_jsonb(s) ->> 'heap_blks_read')::bigint,\n              0\n            )\n          ),\n          0\n        )\n      ),\n      2\n    ) AS ratio\n  FROM pg_statio_user_tables s\n  WHERE NOT schemaname LIKE ANY($1)\n)\nSELECT\n  pg_size_pretty(pg_database_size($2)) AS database_size,\n  COALESCE((SELECT size FROM total_objects WHERE relkind = 'i'), '0 bytes') AS total_index_size,\n  COALESCE((SELECT size FROM total_objects WHERE relkind = 'r'), '0 bytes') AS total_table_size,\n  COALESCE((SELECT size FROM total_objects WHERE relkind = 't'), '0 bytes') AS total_toast_size,\n  COALESCE((SELECT (now() - stats_reset)::text FROM extensions.pg_stat_statements_info), 'N/A') AS time_since_stats_reset,\n  (SELECT COALESCE(ratio::text, 'N/A') FROM cache_hit WHERE relkind = 'i') AS index_hit_rate,\n  (SELECT COALESCE(ratio::text, 'N/A') FROM cache_hit WHERE relkind = 't') AS table_hit_rate,\n  COALESCE((SELECT pg_size_pretty(SUM(size)) FROM pg_ls_waldir()), '0 bytes') AS wal_size",
  expectedKeys: ["database_size", "total_index_size", "total_table_size", "total_toast_size", "time_since_stats_reset", "index_hit_rate", "table_hit_rate", "wal_size"],
  params: (context) => [SCHEMA_PATTERNS, context.databaseName],
  source: "https://raw.githubusercontent.com/supabase/cli/713129cc1cd27c1d9371554d870c2972914ab12b/apps/cli/src/legacy/commands/inspect/db/db-stats/db-stats.query.ts",
};
