// SQL snapshot from Supabase CLI commit 713129cc1cd27c1d9371554d870c2972914ab12b.
// Source: https://raw.githubusercontent.com/supabase/cli/713129cc1cd27c1d9371554d870c2972914ab12b/apps/cli/src/legacy/commands/inspect/db/index-stats/index-stats.query.ts
import type { QueryDefinition } from "../registry";
import { SCHEMA_PATTERNS } from "../schemas";

export const query: QueryDefinition = {
  id: "index-stats",
  title: "Index statistics",
  sql: "-- Combined index statistics: size, usage percent, seq scans, mark unused, expose table + columns\nWITH idx_sizes AS (\n  SELECT\n    i.indexrelid AS oid,\n    FORMAT('%I.%I', n.nspname, c.relname) AS name,\n    FORMAT('%I.%I', tn.nspname, tc.relname) AS table_name,\n    (\n      SELECT STRING_AGG(pg_get_indexdef(i.indexrelid, ord::int, false), ',' ORDER BY ord)\n      FROM unnest(i.indkey::int[]) WITH ORDINALITY AS k(attnum, ord)\n    ) AS columns,\n    pg_relation_size(i.indexrelid) AS index_size_bytes\n  FROM pg_stat_user_indexes ui\n  JOIN pg_index i ON ui.indexrelid = i.indexrelid\n  JOIN pg_class c ON ui.indexrelid = c.oid\n  JOIN pg_namespace n ON c.relnamespace = n.oid\n  JOIN pg_class tc ON tc.oid = i.indrelid\n  JOIN pg_namespace tn ON tn.oid = tc.relnamespace\n  WHERE NOT n.nspname LIKE ANY($1::text[])\n),\nidx_usage AS (\n  SELECT\n    indexrelid AS oid,\n    idx_scan::bigint AS idx_scans\n  FROM pg_stat_user_indexes ui\n  WHERE NOT schemaname LIKE ANY($1::text[])\n),\nseq_usage AS (\n  SELECT\n    relid AS oid,\n    seq_scan::bigint AS seq_scans\n  FROM pg_stat_user_tables\n  WHERE NOT schemaname LIKE ANY($1::text[])\n),\nusage_pct AS (\n  SELECT\n    u.oid,\n    CASE\n      WHEN u.idx_scans IS NULL OR u.idx_scans = 0 THEN 0\n      WHEN s.seq_scans IS NULL THEN 100\n      ELSE ROUND(100.0 * u.idx_scans / (s.seq_scans + u.idx_scans), 1)\n    END AS percent_used\n  FROM idx_usage u\n  LEFT JOIN seq_usage s ON s.oid = u.oid\n)\nSELECT\n  s.name,\n  s.table_name AS \"table\",\n  s.columns,\n  pg_size_pretty(s.index_size_bytes) AS size,\n  COALESCE(up.percent_used, 0)::text || '%' AS percent_used,\n  COALESCE(u.idx_scans, 0) AS index_scans,\n  COALESCE(sq.seq_scans, 0) AS seq_scans,\n  CASE WHEN COALESCE(u.idx_scans, 0) = 0 THEN true ELSE false END AS unused\nFROM idx_sizes s\nLEFT JOIN idx_usage u ON u.oid = s.oid\nLEFT JOIN seq_usage sq ON sq.oid = s.oid\nLEFT JOIN usage_pct up ON up.oid = s.oid\nORDER BY s.index_size_bytes DESC",
  expectedKeys: ["name", "table", "columns", "size", "percent_used", "index_scans", "seq_scans", "unused"],
  params: (context) => [SCHEMA_PATTERNS],
  source: "https://raw.githubusercontent.com/supabase/cli/713129cc1cd27c1d9371554d870c2972914ab12b/apps/cli/src/legacy/commands/inspect/db/index-stats/index-stats.query.ts",
};
