// SQL snapshot from Supabase CLI commit 713129cc1cd27c1d9371554d870c2972914ab12b.
// Source: https://raw.githubusercontent.com/supabase/cli/713129cc1cd27c1d9371554d870c2972914ab12b/apps/cli/src/legacy/commands/inspect/db/vacuum-stats/vacuum-stats.query.ts
import type { QueryDefinition } from "../registry";
import { SCHEMA_PATTERNS } from "../schemas";

export const query: QueryDefinition = {
  id: "vacuum-stats",
  title: "Vacuum statistics",
  sql: "WITH table_opts AS (\n  SELECT\n    pg_class.oid, relname, nspname, array_to_string(reloptions, '') AS relopts\n  FROM\n    pg_class INNER JOIN pg_namespace ns ON relnamespace = ns.oid\n), vacuum_settings AS (\n  SELECT\n    oid, relname, nspname,\n    CASE\n      WHEN relopts LIKE '%autovacuum_vacuum_threshold%'\n        THEN substring(relopts, '.*autovacuum_vacuum_threshold=([0-9.]+).*')::integer\n        ELSE current_setting('autovacuum_vacuum_threshold')::integer\n      END AS autovacuum_vacuum_threshold,\n    CASE\n      WHEN relopts LIKE '%autovacuum_vacuum_scale_factor%'\n        THEN substring(relopts, '.*autovacuum_vacuum_scale_factor=([0-9.]+).*')::real\n        ELSE current_setting('autovacuum_vacuum_scale_factor')::real\n      END AS autovacuum_vacuum_scale_factor,\n    CASE\n      WHEN relopts LIKE '%autovacuum_analyze_threshold%'\n        THEN substring(relopts, '.*autovacuum_analyze_threshold=([0-9.]+).*')::integer\n        ELSE current_setting('autovacuum_analyze_threshold')::integer\n      END AS autovacuum_analyze_threshold,\n    CASE\n      WHEN relopts LIKE '%autovacuum_analyze_scale_factor%'\n        THEN substring(relopts, '.*autovacuum_analyze_scale_factor=([0-9.]+).*')::real\n        ELSE current_setting('autovacuum_analyze_scale_factor')::real\n      END AS autovacuum_analyze_scale_factor\n  FROM\n    table_opts\n)\nSELECT\n  FORMAT('%I.%I', vacuum_settings.nspname, vacuum_settings.relname) AS name,\n  coalesce(to_char(psut.last_vacuum, 'YYYY-MM-DD HH24:MI'), '') AS last_vacuum,\n  coalesce(to_char(psut.last_autovacuum, 'YYYY-MM-DD HH24:MI'), '') AS last_autovacuum,\n  coalesce(to_char(psut.last_analyze, 'YYYY-MM-DD HH24:MI'), '') AS last_analyze,\n  coalesce(to_char(psut.last_autoanalyze, 'YYYY-MM-DD HH24:MI'), '') AS last_autoanalyze,\n  to_char(pg_class.reltuples, '9G999G999G999') AS rowcount,\n  to_char(psut.n_dead_tup, '9G999G999G999') AS dead_rowcount,\n  to_char(autovacuum_vacuum_threshold\n       + (autovacuum_vacuum_scale_factor::numeric * pg_class.reltuples), '9G999G999G999') AS autovacuum_threshold,\n  CASE\n    WHEN autovacuum_vacuum_threshold + (autovacuum_vacuum_scale_factor::numeric * pg_class.reltuples) < psut.n_dead_tup\n    THEN 'yes'\n    ELSE 'no'\n  END AS expect_autovacuum,\n  to_char(autovacuum_analyze_threshold\n       + (autovacuum_analyze_scale_factor::numeric * pg_class.reltuples), '9G999G999G999') AS autoanalyze_threshold,\n  CASE\n    WHEN autovacuum_analyze_threshold + (autovacuum_analyze_scale_factor::numeric * pg_class.reltuples) < psut.n_dead_tup\n    THEN 'yes'\n    ELSE 'no'\n  END AS expect_autoanalyze\nFROM\n  pg_stat_user_tables psut INNER JOIN pg_class ON psut.relid = pg_class.oid\nINNER JOIN vacuum_settings ON pg_class.oid = vacuum_settings.oid\nWHERE NOT vacuum_settings.nspname LIKE ANY($1::text[])\nORDER BY\n  case\n    when pg_class.reltuples = -1 then 1\n    else 0\n  end,\n  1",
  expectedKeys: ["name", "last_vacuum", "last_autovacuum", "last_analyze", "last_autoanalyze", "rowcount", "dead_rowcount", "expect_autovacuum", "expect_autoanalyze"],
  params: (context) => [SCHEMA_PATTERNS],
  source: "https://raw.githubusercontent.com/supabase/cli/713129cc1cd27c1d9371554d870c2972914ab12b/apps/cli/src/legacy/commands/inspect/db/vacuum-stats/vacuum-stats.query.ts",
};
